### ISSUE TITLE
Downloads fine, but then clicks on the "click here for manual download" option which just downloads it twice to a place I dont want it.

### ISSUE THREAD

**Issue by CrazyDrunkenIrishDude** [parsiad/nexus-autodl#27]
When Wabbajack is full on its queue, the "If you are having trouble, [click here] to download manually" screen pops up for a second, enough time for the autodl to click on it, is there anyway for it to not click here?

**Comment by Semiotikal** [comment]
Yup, this happened to me as well. Every download is being duplicated because pyautogui has a pattern to both click the Slow Download button but also the Click Here URL.

Using in wabbajack results in it downloading it both through the app (and therefore into the filepath specified for download artefacts) and se

 This second part isnt necessary as the slow download will begin automatically.

here's a snippet from the logs

04/01/2024 07:32:31 PM [INFO] Sleeping for 2.499352 seconds`
04/01/2024 07:32:35 PM [INFO] Saving current mouse position at x=1177.000000 y=716.000000
04/01/2024 07:32:35 PM [INFO] Clicking on click_here at coordinates x=1055.601196 y=618.561829
04/01/2024 07:32:35 PM [INFO] Sleeping for 3.826686 seconds
04/01/2024 07:32:39 PM [INFO] Saving current mouse position at x=2429.000000 y=542.000000
04/01/2024 07:32:39 PM [INFO] Clicking on slow_download at coordinates x=796.238129 y=761.236938
04/01/2024 07:32:39 PM [INFO] Sleeping for 0.739780 seconds
04/01/2024 07:32:41 PM [INFO] No matches found
04/01/2024 07:32:41 PM [INFO] Sleeping for 1.441626 seconds
04/01/2024 07:32:43 PM [INFO] No matches found
04/01/2024 07:32:43 PM [INFO] Sleeping for 1.872921 seconds
04/01/2024 07:32:46 PM [INFO] Saving current mouse position at x=2286.000000 y=1904.000000
04/01/2024 07:32:46 PM [INFO] Clicking on click_here at coordinates x=770.023376 y=520.675964

# Solutions

1. Remove the Click Here template image (see asociated PR) 

**or**

2. Increase the time that the script sleeps after clicking an initial download (more than 5 seconds).

**Comment by parsiad** [comment]
There is a new release; please consider updating.
